test: &default

  # Credentials for REST APIs
  client_id: AQc7ebWXWNQBbWuFuCxRflxO-ar9sFATocv8VUs81RG4q7_G4vxRrxoYfF37yY_s83I-mPFALMMkTgTB
  client_secret: EAXwxjovbwem7BA_1QBFbEEun3bqhpa5jqsBdJgn1rwalw72yWO01CyWmEaYLPeKu6fFQZ8WkTfecWH7

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: jb-us-seller_api1.paypal.com
  # password: WX4WTU3S8MY44S7F
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: shikhir@expoai.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
